title:             MOUNTAIN DU
email:             dulongyuan@gmail.com
description:       The mountains are calling and I must go.  - John Muir
author:            Longyuan Du
baseurl:           "/blog/"
url:               "http://www.longyuandu.com/blog/"

# Social Profiles
# twitter_username:  SBootstrap
# github_username:   BlackrockDigital
# acebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

permalink: /:year/:month/:title:output_ext
