title:             MOUNTAIN DU
email:             dulongyuan@gmail.com
description:       The mountains are calling, and I must go.
author:            Longyuan Du
#baseurl:           "/blog"
url:               "http://www.longyuandu.com/blog/"

# Social Profiles
twitter_username:  SBootstrap
# github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
